### ISSUE TITLE
Debug Usage guideline

### ISSUE THREAD

**Issue by jiayaozhang** [archibate/debug-hpp#1]
```
    debug(), b;
    std::vector<std::string> c{"hello", "world"};
    debug(), c;
    std::map<std::string, int> d{{"hello", 1}, {"world", 2}};
```
案例里面，debug()一行里面只能有一个b或者c，
假如我的文件里面想要用一行把所有信息都打出来该怎么写呢？

比如这种代码
```Log(" Node %s has %i vertices, %i convex, %i LODS, Node->name, Node->Mesh->GetVertexCount(), Node->Mesh->GetConvexCount(), Node->Mesh->GetLODsCount());```

如果改用在debug()该怎么写呢？

**Comment by archibate** [comment]
逗号分割
debug(), “Node”, node.vertexCount(), “has”;









无法顺畅的大口呼吸，是活着的最好证明

---Original---
From: "Jiayao Zhang ***@***.***&gt;
Date: Thu, May 23, 2024 16:38 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [archibate/debug-hpp] Debug Usage guideline (Issue #1)




     debug(), b;     std::vector<std::string&gt; c{"hello", "world"};     debug(), c;     std::map<std::string, int&gt; d{{"hello", 1}, {"world", 2}};  
案例里面，debug()一行里面只能有一个b或者c，
 假如我的文件里面想要用一行把所有信息都打出来该怎么写呢？
 
比如这种代码
 Log(" Node %s has %i vertices, %i convex, %i LODS, Node-&gt;name, Node-&gt;Mesh-&gt;GetVertexCount(), Node-&gt;Mesh-&gt;GetConvexCount(), Node-&gt;Mesh-&gt;GetLODsCount());
 
如果改用在debug()该怎么写呢？
