### ISSUE TITLE
没有正确处理unsigned char类型

### ISSUE THREAD

**Issue by heheda123123** [archibate/debug-hpp#3]
如图可以看到，当unsigned char类型中是不可见字符时，没有像char那样输出十六进制格式
![image](https://github.com/user-attachments/assets/662ffaca-5c11-4e32-bc75-11e2b3a7ea14)
必须设置DEBUG_UNSIGNED_AS_HEXADECIMAL 1才会输出char那样的格式

文档中说无符号数字默认是十进制，但是这里也不是按十进制

另外我觉得对于无符号数字，默认十六进制是否合理一些
比如对于加密后的数据，常用vector<uint8_t>。调试的时候都是输出十六进制方便看一些

**Comment by archibate** [comment]
修复了unsigned char打印为字符而不是十进制的错误。

添加了hexdump功能。
```cpp
    std::string z15 = "\xde\xad\xbe\xaf"; // 任意 uint8_t 容器
    debug(), debug::hexdump(z15);
```
输出：
```
  0.000 [131003134371264] test.cpp:179:  DE AD BE AF
```

**Comment by heheda123123** [comment]
辛苦小彭老师了， 请你喝杯咖啡
